

title: Timeseries new covid cases by county
url: "https://jrkhan.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  jrkhan

theme: jekyll-theme-cayman

#plugins:
#  - jekyll-feed


exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
   - Gemfile
   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
